club = []
club += ["Club Football: Ajax"]
club += ["Club Football: Arsenal"]
club += ["Club Football: Aston Villa"]
club += ["Club Football: Barcelona"]
club += ["Club Football: Bayern Munich"]
club += ["Club Football: Borussia Dortmund"]
club += ["Club Football: Celtic"]
club += ["Club Football: Chelsea"]
club += ["Club Football: Hamburger"]
club += ["Club Football: Inter Milan"]
club += ["Club Football: Juventus"]
club += ["Club Football: Leeds United"]
club += ["Club Football: Liverpool"]
club += ["Club Football: Manchester United"]
club += ["Club Football: Milan"]
club += ["Club Football: Rangers"]
club += ["Club Football: Real Madrid"]

club2005 = []
club2005 += ["Club Football 2005: Ajax"]
club2005 += ["Club Football 2005: Arsenal"]
club2005 += ["Club Football 2005: Aston Villa"]
club2005 += ["Club Football 2005: Barcelona"]
club2005 += ["Club Football 2005: Bayern Munich"]
club2005 += ["Club Football 2005: Birmingham City"]
club2005 += ["Club Football 2005: Borussia Dortmund"]
club2005 += ["Club Football 2005: Celtic"]
club2005 += ["Club Football 2005: Chelsea"]
club2005 += ["Club Football 2005: Hamburger"]
club2005 += ["Club Football 2005: Inter Milan"]
club2005 += ["Club Football 2005: Juventus"]
club2005 += ["Club Football 2005: Liverpool"]
club2005 += ["Club Football 2005: Manchester United"]
club2005 += ["Club Football 2005: Milan"]
club2005 += ["Club Football 2005: Newcastle United"]
club2005 += ["Club Football 2005: Olympique de Marseille"]
club2005 += ["Club Football 2005: Paris Saint-Germain"]
club2005 += ["Club Football 2005: Rangers"]
club2005 += ["Club Football 2005: Real Madrid"]
club2005 += ["Club Football 2005: Tottenham Hotspur"]

alias = {}
alias["Airforce Delta Storm / Deadly Skies"] = ["Airforce Delta Storm"]
alias["Alfa Romeo Racing Italiano / SCAR : Squadra Corse Alfa Romeo"] = ["Alfa Romeo Racing Italiano"]
alias["Aliens vs Predator: Extinction"] = ["Aliens Versus Predator: Extinction"]
alias["Break Nine: World Billiards Tournament [JP]"] = ["Break Nine: World Billiards Tournament"]
alias["C.A.T.: Cyber Attack Team [JP]"] = ["C.A.T.: Cyber Attack Team"]
alias["Capcom Fighting Jam (PAL)"] = ["Capcom Fighting Evolution"]
alias["Championship Manager 2006 [EU]"] = ["Championship Manager 2006"]
alias["Championship Manager 5 [EU]"] = ["Championship Manager 5"]
alias["Championship Manager: Season 01/02 [EU]"] = ["Championship Manager: Season 01/02"]
alias["Championship Manager: Season 02/03 [EU]"] = ["Championship Manager: Season 02/03"]
alias['Club Football [EU]'] = club
alias['Club Football 2005 [EU]'] = club2005
alias["Cricket 2005 [EU]"] = ["Cricket 2005"]
alias["Daemon Vector[Asia]"] = ["Daemon Vector"]
alias["Dennou Taisen: DroneZ [JP]"] = ["Dennou Taisen: DroneZ"]
alias["Double S.T.E.A.L. : The Second Clash"] = ["Double-S.T.E.A.L. - The Second Clash"]
alias["England International Football [EU]"] = ["England International Football"]
alias["ExaSkeleton [JP]"] = ["ExaSkeleton"]
alias["F1 Career Challenge [EU]"] = ["F1 Career Challenge"]
alias["Flight Academy [JP]"] = ["Flight Academy"]
alias["Gotcha! [EU]"] = ["Gotcha!"]
alias["Guilty Gear X2 #Reload"] = ["Guilty Gear X2#Reload"]
alias["Harry Potter and the Philosopher's Stone"] = ["Harry Potter and the Sorcerer's Stone"]
alias["International Superstar Soccer 2 [EU]"] = ["International Superstar Soccer 2"]
alias["Jikkyou World Soccer 2002 [JP]"] = ["Jikkyou World Soccer 2002"]
alias["Jockey's Road [JP]"] = ["Jockey's Road"]
alias["Kao the Kangaroo Round 2"] = ["Kao the Kangaroo: Round 2"]
alias["Largo Winch: Empire Under Threat [EU]"] = ["Largo Winch: Empire Under Threat"]
alias["LMA Manager 2003 [EU]"] = ["LMA Manager 2003"]
alias["LMA Manager 2004 [EU]"] = ["LMA Manager 2004"]
alias["LMA Manager 2005 [EU]"] = ["LMA Manager 2005"]
alias["LMA Manager 2006 [EU]"] = ["LMA Manager 2006"]
alias["Manchester United Manager 2005[3] [EU]"] = ["Manchester United Manager 2005"]
alias["Mashed: Drive to Survive"] = ["Drive to Survive"]
alias["Melbourne Cup Challenge[AUS]"] = ["Melbourne Cup Challenge"]
alias["Metal Wolf Chaos [JP]"] = ["Metal Wolf Chaos"]
alias["N.U.D.E.@ Natural Ultimate Digital Experiment [JP]"] = ["N.U.D.E.@ Natural Ultimate Digital Experiment"]
alias["Neighbours from Hell [EU]"] = ["Neighbours from Hell"]
alias["Panzer Elite Action: Fields of Glory [EU]"] = ["Panzer Elite Action: Fields of Glory"]
alias["Petite Copter [JP]"] = ["Petite Copter"]
alias["Plus Plum 2 [JP]"] = ["Plus Plum 2"]
alias["Project Zero II: Crimson Butterfly (PAL)"] = ["Fatal Frame II: Crimson Butterfly"]
alias["Psyvariar 2 [JP]"] = ["Psyvariar 2"]
alias["Rent-A-Hero No. 1 [JP]"] = ["Rent-A-Hero No. 1"]
alias["Robot Wars: Extreme Destruction [EU]"] = ["Robot Wars: Extreme Destruction"]
alias["Rugby Challenge 2006 [EU]"] = ["Rugby Challenge 2006"]
alias["Rugby League 2 [EU]"] = ["Rugby League 2"]
alias["Rugby League [EU]"] = ["Rugby League"]
alias["Sensible Soccer 2006 [EU]"] = ["Sensible Soccer 2006"]
alias["Shadow of Memories [EU]"] = ["Shadow of Memories"]
alias['Shikigami no Shiro Evolution [JP]'] = ['Shikigami no Shiro Evolution Red', 'Shikigami no Shiro Evolution Blue']
alias["Shikigami no Shiro II [JP]"] = ["Shikigami no Shiro II"]
alias["Shikigami no Shiro [JP]"] = ["Shikigami no Shiro"]
alias["Shin Megami Tensei: NINE [JP]"] = ["Shin Megami Tensei: Nine"]
alias["Slam Tennis [EU]"] = ["Slam Tennis"]
alias["Star Wars: Knights Of The Old Republic"] = ["Star Wars: Knights of the Old Republic"]
alias["Taito Legends 2 [EU]"] = ["Taito Legends 2"]
alias["Tenerezza [JP]"] = ["Tenerezza"]
alias["The Wild Rings [JP]"] = ["The Wild Rings"]
alias["Thousand Land [JP]"] = ["Thousand Land"]
alias["TOCA Race Driver (EU)"] = ["Pro Race Driver"]
alias["Total Club Manager 2005 [EU]"] = ["Total Club Manager 2005"]
alias["Tour de France [EU]"] = ["Tour de France"]
alias["UEFA Champions League 2004-2005 [EU]"] = ["UEFA Champions League 2004-2005"]
alias["Ultimate Pro Pinball [EU]"] = ["Ultimate Pro Pinball"]
alias["Winning Eleven 9 (JP)"] = ["World Soccer Winning Eleven 9"]
alias["World Championship Rugby [EU]"] = ["World Championship Rugby"]
alias["World Championship Snooker 2003 [EU]"] = ["World Championship Snooker 2003"]
alias["World Championship Snooker 2004 [EU]"] = ["World Championship Snooker 2004"]
alias["World Snooker Championship 2005 [EU]"] = ["World Snooker Championship 2005"]
alias["Yetisports Arctic Adventure [EU]"] = ["Yetisports Arctic Adventure"]

# Manually added
alias['APEX / Racing Evoluzione'] = ['APEX']
alias['Dancing Stage Unleashed 2'] = ['Dance Dance Revolution Ultramix 2']
alias['Dancing Stage Unleashed 3'] = ['Dance Dance Revolution Ultramix 3']
alias['Dancing Stage Unleashed'] = ['Dance Dance Revolution Ultramix']
alias['Drake'] = ['Drake of the 99 Dragons']
alias['Ex-Chaser(JP)'] = ['Black Stone: Magic & Steel']
alias['Fahrenheit (PAL)'] = ['Indigo Prophecy']
alias['Lakemasters: Bass Fishing Game(JP)'] = ['Pro Cast Sports Fishing']
alias['Pro Evolution Soccer 4 (PAL)'] = ['World Soccer Winning Eleven 8 International']
alias['Pro Evolution Soccer 5 (PAL)'] = ['World Soccer Winning Eleven 9']
alias['Project Zero (PAL)'] = ['Fatal Frame']
alias['TD Overdrive'] = ['Test Drive']

unreleased = {}
unreleased['Kameo Elements of Power'] = {}
unreleased['The Red Star'] = {}
unreleased['Sonic Extreme'] = {}
unreleased['Re-Volt'] = {}
unreleased['Tech Deck Dude Bare Knuckle Grind'] = {}


# From xbox.wikia.com/wiki/Xbox_Live_Arcade
xbla = {}
xbla['Alien Sky'] = {}
xbla['AstroPop'] = {}
xbla['Atomaders'] = {}
xbla['Bankshot Billiards'] = {}
xbla['Bejeweled'] = {}
xbla['Bookworm'] = {}
xbla['Dangerous Mines'] = {}
xbla['Dino and Aliens'] = {}
xbla['Feeding Frenzy '] = {}
xbla['Fuzzee Fever'] = {}
xbla['Gauntlet'] = {}
xbla['Guardian'] = {}
xbla['Hamsterball'] = {}
xbla['Hardwood Solitaire'] = {}
xbla['Joust'] = {}
xbla['Marble Blast Gold'] = {}
xbla['Ms. Pac-Man'] = {}
xbla['Mutant Storm'] = {}
xbla['Namco Vintage'] = {} # Includes: (Pole Position, Dig Dug, & Galaga)
xbla['Orbz'] = {}
xbla['Pipeline'] = {}
xbla['Ricochet Lost Worlds'] = {}
xbla['Robotron: 2084'] = {}
xbla['Smash TV'] = {}
xbla['Super Collapse II'] = {}
xbla['ThinkTanks'] = {}
xbla['Zuma'] = {}
